#### general settings
name: 667_EDVR_SR_VIDEO_BASEx4_VIMEO90K_VHS
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: Vimeo90K
    mode: Vimeo90K
    dataroot_GT: F:\projects\ai\vhs\vhs_sequences_GT.lmdb
    dataroot_LQ: F:\projects\ai\vhs_sequences_matlabLRx4.lmdb
    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
    interval_list: [1]
    N_frames: 7
  val:
    name: VHS
    mode: Vimeo90K
    dataroot_GT: F:\projects\ai\vhs\vhs_GT.lmdb
    dataroot_LQ: F:\projects\ai\vhs_vhs_matlabLRx4.lmdb
    interval_list: [1]
    N_frames: 7

#### network structures
network_G:
  which_model_G: EDVR
  nf: 128
  nframes: 7
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: false
  HR_in: false
  w_TSA: true
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_G: F:\projects\ai\mmsr\experiments\pretrained_models\EDVR_Vimeo90K_SR_L.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
